config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end
  
  namespace :appointment do
    get 'steps/show'
    get 'steps/update'
  end
  get 'users/index'
  get 'users/show'
  
  devise_for :users, :skip => [:registration], :controllers => { :users => "users" }
    as :user do
      authenticated :user do
      root "pages#dashboard", as: :authenticated_root
      end
    
      unauthenticated :user do
        root "pages#home", as: :unauthenticated_root
    end
  end
  
  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  
  resources :users, except: [:destroy], concerns: [:with_datatable]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  
  resources :appointments, concerns: [:with_datatable] do
    resources :steps, only: [:show, :update], controller: 'appointment/steps'
    
    member do
      get 'assign_doctor'
      get 'cancel'
    end
  end
  
  
  resources :procedures, concerns: [:with_datatable] do
    member do
      get 'show_timeslots'
    end
  end
  
  
  resources :payments, concerns: [:with_datatable]
    
  
  
  resources :timeslots do
    member do
      get 'remove_time'
    end 
  end
  
 get 'reports/dashboard', to: 'reports#dashboard'
 get 'update_report', to: 'reports#update_report'
 get 'download_appointments_report', to: 'reports#download_appointments_report'
 get 'download_procedures_report', to: 'reports#download_procedures_report'
 get 'download_payments_report', to: 'reports#download_payments_report'
 get 'gp', to: 'pages#gp'
  
end

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer flex-shrink-0 py-4 text-white" style="background-color: var(--blue);">
<div class="container">
  <div class="row align-items-center">
    <div class="col-6">
      <h2>Contact</h2>
      <p>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-phone" width="52" height="52" viewBox="0 0 24 24" stroke-width="2" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
          <path d="M5 4h4l2 5l-2.5 1.5a11 11 0 0 0 5 5l1.5 -2.5l5 2v4a2 2 0 0 1 -2 2a16 16 0 0 1 -15 -15a2 2 0 0 1 2 -2" />
        </svg>
        1 264 497 3053
      </p>
      <p>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-mail" width="64" height="64" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
          <rect x="3" y="5" width="18" height="14" rx="2" />
          <polyline points="3 7 12 13 21 7" />
        </svg>
        appointments@hughesmedical.com
      </p>
      <p>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-map-2" width="64" height="64" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
          <line x1="18" y1="6" x2="18" y2="6.01" />
          <path d="M18 13l-3.5 -5a4 4 0 1 1 7 0l-3.5 5" />
          <polyline points="10.5 4.75 9 4 3 7 3 20 9 17 15 20 21 17 21 15" />
          <line x1="9" y1="4" x2="9" y2="17" />
          <line x1="15" y1="15" x2="15" y2="20" />
        </svg>
        Lower South Hill, Anguilla
      </p> <br>
      <%= link_to 'Terms of Service', 'https://hughesmedical.com/terms-of-service/', class:'text-white' %> | <%= link_to 'Privacy Policy', 'https://hughesmedical.com/privacy-policy/', class:'text-white' %> | <%= link_to 'Refund Policy', 'https://hughesmedical.com/refund-policy/', class:'text-white' %>

    </div>
    <div class="col-6 text-white">
      <h2>About</h2>
      <p>
       Welcome to Hughes Medical Centre, a private healthcare clinic with </br>
       a wide range of services and compassionate providers. Our services range </br>
       from cosmetic and reconstructive surgeries, to ambulatory care and counselling.</br></p>

        <p>@ <%= Date.today.year %> Hughes Medical Centre. All Rights Reserved</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-expand-md navbar-dark d-print-none">
  <div class="container-xl">
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">

    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item d-none d-md-flex me-3">
        <div class="btn-list">
          <a href="https://github.com/tabler/tabler" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/brand-github -->
            About
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            Contact Us
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            Privacy Policy
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            Refund Policy
          </a>
        </div>
      </div>
    <!--- logins for Users -->
    </div>
  </div>
</header>

<header class="navbar navbar-expand-md navbar-light d-print-none nav-shadow">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to root_path, class:'navbar-brand pe-md-3' do %>
      <%= image_tag("HMC-logo.png", width: 50, class: 'mr-4') %>
      <span style="padding-left: 10px;">Hughes Medical Centre</span>
    <% end %>
    <div class="navbar-expand-md">
      <div class="collapse navbar-collapse" id="navbar-menu">
        <div class="navbar navbar-light">
          <div class="container-xl justify-content-md-center">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="https://3b807202c7554c298ebd3679cf736a2f.vfs.cloud9.us-east-2.amazonaws.com/">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                       <path d="M5 12l-2 0l9 -9l9 9l-2 0m-14 0v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7m-10 9v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                    </svg>             
                  </span>
                  <span class="nav-link-title">
                    Home
                  </span>
                </a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/package -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-medicine-syrup" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                       <path d="M8 21h8a1 1 0 0 0 1 -1v-10a3 3 0 0 0 -3 -3h-4a3 3 0 0 0 -3 3v10a1 1 0 0 0 1 1zm2 -7h4m-2 -2v4m-2 -9v-3a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v3"></path>
                    </svg>
                  </span>
                  <span class="nav-link-title">
                    GP
                  </span>
                </a>
                <div class="dropdown-menu">
                  <% Procedure.find_procedure_by_type(0).each do |procedure| %>
                    <%= link_to procedure.name, procedure_path(procedure), class:'dropdown-item' %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/checkbox -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-vaccine" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                       <path d="M17 3l4 4m-2 -2l-4.5 4.5m-3 -3l6 6m-1 -1l-6.5 6.5h-4v-4l6.5 -6.5m-5 5l1.5 1.5m1.5 -4.5l1.5 1.5m-9 10l3 -3"></path>
                    </svg>
                  </span>
                  <span class="nav-link-title">
                    Vaccinations
                  </span>
                </a>
                <div class="dropdown-menu">
                  <% Procedure.find_procedure_by_type(1).each do |procedure| %>
                    <%= link_to procedure.name, procedure_path(procedure), class:'dropdown-item' %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-extra" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/star -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-microscope" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                     <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                     <path d="M5 21h14m-13 -3h2m-1 0v3m2 -10l3 3l6 -6l-3 -3zm1.5 1.5l-1.5 1.5m8 -11l3 3m-8 15a6 6 0 0 0 3.715 -10.712"></path>
                    </svg>
                  </span>
                  <span class="nav-link-title">
                    Tests
                  </span>
                </a>
                <div class="dropdown-menu">
                  <% Procedure.find_procedure_by_type(2).each do |procedure| %>
                    <%= link_to procedure.name, procedure_path(procedure), class:'dropdown-item' %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-layout" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/layout-2 -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><rect x="4" y="4" width="6" height="5" rx="2"></rect><rect x="4" y="13" width="6" height="7" rx="2"></rect><rect x="14" y="4" width="6" height="7" rx="2"></rect><rect x="14" y="15" width="6" height="5" rx="2"></rect></svg>
                  </span>
                  <span class="nav-link-title">
                    Surgery
                  </span>
                 </span>
                </a>
                <div class="dropdown-menu">
                  <% Procedure.find_procedure_by_type(3).each do |procedure| %>
                    <%= link_to procedure.name, procedure_path(procedure), class:'dropdown-item' %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-layout" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/layout-2 -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-wand" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                       <path d="M6 21l15 -15l-3 -3l-15 15l3 3m9 -15l3 3m-9 -6a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2m10 10a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2"></path>
                    </svg>
                  </span>
                  <span class="nav-link-title">
                    Specialist
                  </span>
                 </span>
                </a>
                <div class="dropdown-menu">
                  <% Procedure.find_procedure_by_type(4).each do |procedure| %>
                    <%= link_to procedure.name, procedure_path(procedure), class:'dropdown-item' %>
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
  
<!--------- Second level navbar -------->

app/views/shared/_page_header.html.erb
<div class="page-header d-print-none mb-4">
  <div class="row g-3 align-items-center">
    <% if defined?(back_action) %>
      <div class="col-auto">
        <%= link_to back_action do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-left" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
             <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
             <line x1="5" y1="12" x2="19" y2="12"></line>
             <line x1="5" y1="12" x2="11" y2="18"></line>
             <line x1="5" y1="12" x2="11" y2="6"></line>
          </svg>
        <% end %>
      </div>
    <% end %>
    <div class="col">
      <% if defined?(pre_title) %>
        <h2 class="page-pretitle mb-0">
          <%= pre_title %>
        </h2>
      <% end %>
      <h2 class=" page-title">
        <%= title %>
      </h2>
    </div>
    <% if defined?(action) %>
      <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">
          <%= link_to action, class: "btn btn-primary" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
            <%= action_name %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_user_navbar.html.erb
<header class="navbar navbar-expand-md navbar-dark d-print-none">
  <div class="container-xl">
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">

    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item d-none d-md-flex mx-4 ">
        <div class="btn-list">
          <a href="https://github.com/tabler/tabler" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/brand-github -->
            About
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            Contact Us
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            Privacy Policy
          </a>
          <a href="https://github.com/sponsors/codecalm" class="btn btn-dark fw-light border-0" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
            Refund Policy
          </a>
        </div>
      </div>
      <div class="navbar-nav flex-row order-md-last">
        <div class="nav-item dropdown">
          <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu" aria-expanded="false">
            <span class="avatar bg-light me-2"><%= current_user.initials %></span>
            <div class="d-none d-xl-block ps-2">
              <div><%= current_user.name %></div>
              <div class="mt-1 small"><%= current_user.role%></div>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<header class="navbar navbar-expand-md navbar-light d-print-none nav-shadow">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to root_path, class:'navbar-brand pe-md-3' do %>
      <%= image_tag("HMC-logo.png", width: 50, class: 'mr-4') %>
      <span style="padding-left: 10px;">Hughes Medical Centre</span>
    <% end %>
    <div class="navbar-expand-md">
      <div class="collapse navbar-collapse" id="navbar-menu">
        <div class="navbar navbar-light">
          <div class="container-xl justify-content-md-center">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="https://3b807202c7554c298ebd3679cf736a2f.vfs.cloud9.us-east-2.amazonaws.com/">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="5 12 3 12 12 3 21 12 19 12"></polyline><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path></svg>
                  </span>
                  <span class="nav-link-title">
                    Home
                  </span>
                </a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/package -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"></polyline><line x1="12" y1="12" x2="20" y2="7.5"></line><line x1="12" y1="12" x2="12" y2="21"></line><line x1="12" y1="12" x2="4" y2="7.5"></line><line x1="16" y1="5.25" x2="8" y2="9.75"></line></svg>
                  </span>
                  <span class="nav-link-title">
                    Appointments
                  </span>
                </a>
                <div class="dropdown-menu">
                  <%= link_to 'All Appointments', appointments_path, class:'dropdown-item' %>
                  <%= link_to 'New Appointment', new_appointment_path, class:'dropdown-item' %>
                </div>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/package -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"></polyline><line x1="12" y1="12" x2="20" y2="7.5"></line><line x1="12" y1="12" x2="12" y2="21"></line><line x1="12" y1="12" x2="4" y2="7.5"></line><line x1="16" y1="5.25" x2="8" y2="9.75"></line></svg>
                  </span>
                  <span class="nav-link-title">
                    Procedures
                  </span>
                </a>
                <div class="dropdown-menu">
                  <%= link_to 'All Procedures', procedures_path, class:'dropdown-item' %>
                  <%= link_to 'New Procedure', new_procedure_path, class:'dropdown-item' %>
                </div>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/package -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"></polyline><line x1="12" y1="12" x2="20" y2="7.5"></line><line x1="12" y1="12" x2="12" y2="21"></line><line x1="12" y1="12" x2="4" y2="7.5"></line><line x1="16" y1="5.25" x2="8" y2="9.75"></line></svg>
                  </span>
                  <span class="nav-link-title">
                    Payments
                  </span>
                </a>
                <div class="dropdown-menu">
                  <%= link_to 'All Payments', payments_path, class:'dropdown-item' %>
                </div>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false">
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/package -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"></polyline><line x1="12" y1="12" x2="20" y2="7.5"></line><line x1="12" y1="12" x2="12" y2="21"></line><line x1="12" y1="12" x2="4" y2="7.5"></line><line x1="16" y1="5.25" x2="8" y2="9.75"></line></svg>
                  </span>
                  <span class="nav-link-title">
                    Users
                  </span>
                </a>
                <div class="dropdown-menu">
                  <%= link_to 'All Users', users_path, class:'dropdown-item' %>
                  <%= link_to 'New user', '#', class:'dropdown-item' %>
                </div>
              </li>
              
      
              <li class="nav-item">
                <%= link_to reports_dashboard_path, class:"nav-link" do %>
                  <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/package -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"></polyline><line x1="12" y1="12" x2="20" y2="7.5"></line><line x1="12" y1="12" x2="12" y2="21"></line><line x1="12" y1="12" x2="4" y2="7.5"></line><line x1="16" y1="5.25" x2="8" y2="9.75"></line></svg>
                  </span>
                  <span class="nav-link-title">Reports</span>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
  
<!--------- Second level navbar -------->