config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end
  
  namespace :appointment do
    get 'steps/show'
    get 'steps/update'
  end
  get 'users/index'
  get 'users/show'
  
  devise_for :users, :skip => [:registration], :controllers => { :users => "users" }
    as :user do
      authenticated :user do
      root "pages#dashboard", as: :authenticated_root
      end
    
      unauthenticated :user do
        root "pages#home", as: :unauthenticated_root
    end
  end
  
  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  
  resources :users, except: [:destroy], concerns: [:with_datatable]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  
  resources :appointments, concerns: [:with_datatable] do
    resources :steps, only: [:show, :update], controller: 'appointment/steps'
    
    member do
      get 'assign_doctor'
      get 'cancel'
    end
  end
  
  
  resources :procedures, concerns: [:with_datatable] do
    member do
      get 'show_timeslots'
    end
  end
  
  
  resources :payments, concerns: [:with_datatable]
    
  
  
  resources :timeslots do
    member do
      get 'remove_time'
    end 
  end
  
 get 'reports/dashboard', to: 'reports#dashboard'
 get 'update_report', to: 'reports#update_report'
 get 'download_appointments_report', to: 'reports#download_appointments_report'
 get 'download_procedures_report', to: 'reports#download_procedures_report'
 get 'download_payments_report', to: 'reports#download_payments_report'
 get 'gp', to: 'pages#gp'
  
end

app/views/pages/dashboard.html.erb
<div class="container">
    <div class="row row-deck row-cards my-4">
      <div class="col-lg-6">
        <div class="card p-4">
          <%= render 'shared/page_header', pre_title: "Welcome, #{current_user.first_name}", title: "Dashboard" %>
          <p  class="text-primary mt-1"><%= format_date(Date.today) %></p>
          
          <div class="row align-items-center">
            <div class="col-auto">
              <span class="text-white avatar" style="background-color: #003F5D"><!-- Download SVG icon from http://tabler-icons.io/i/currency-dollar -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4"></path>
                  <path d="M18 18m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                  <path d="M15 3v4"></path>
                  <path d="M7 3v4"></path>
                  <path d="M3 11h16"></path>
                  <path d="M18 16.496v1.504l1 1"></path>
                </svg>
              </span>
            </div>
            <div class="col">
              <div class="font-weight-medium">
                <%= Appointment.all.active.count %>
                <!--- Need to make these active appointments -->
              </div>
              <div class="text-muted">
                Total Appointments
              </div>
            </div>
          </div>
          
          <hr>
          
          <div class="row row-cards">
            <div class="col-lg-6">
              <div class="row">
                <div class="col-auto">
                  <span class="text-white avatar" style="background-color: #004987"><!-- Download SVG icon from http://tabler-icons.io/i/currency-dollar -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-medicine-syrup" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M8 21h8a1 1 0 0 0 1 -1v-10a3 3 0 0 0 -3 -3h-4a3 3 0 0 0 -3 3v10a1 1 0 0 0 1 1z"></path>
                      <path d="M10 14h4"></path>
                      <path d="M12 12v4"></path>
                      <path d="M10 7v-3a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v3"></path>
                    </svg>                  
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Appointment.type_count('General') %>
                  </div>
                  <div class="text-muted">
                    General Appointments
                  </div>
                </div>
              </div>
            </div>
            
            <div class="col-lg-6">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="text-white avatar" style="background-color: #004F92"><!-- Download SVG icon from http://tabler-icons.io/i/shopping-cart -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-layout-2" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M4 4m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                      <path d="M4 13m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                      <path d="M14 4m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                      <path d="M14 15m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                    </svg>
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Appointment.type_count('Surgery') %>
                  </div>
                  <div class="text-muted">
                    Surgery Appointments
                  </div>
                </div>
              </div>
            </div>
            
            <div class="col-lg-6">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="text-white avatar" style="background-color: #00569D"><!-- Download SVG icon from http://tabler-icons.io/i/brand-twitter -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-microscope" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M5 21h14"></path>
                      <path d="M6 18h2"></path>
                      <path d="M7 18v3"></path>
                      <path d="M9 11l3 3l6 -6l-3 -3z"></path>
                      <path d="M10.5 12.5l-1.5 1.5"></path>
                      <path d="M17 3l3 3"></path>
                      <path d="M12 21a6 6 0 0 0 3.715 -10.712"></path>
                    </svg>
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Appointment.type_count('Test') %>
                  </div>
                  <div class="text-muted">
                    Test Appointments
                  </div>
                </div>
              </div>
            </div>
            
            <div class="col-lg-6">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="text-white avatar" style="background-color: #006DB2"><!-- Download SVG icon from http://tabler-icons.io/i/brand-facebook -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-vaccine" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M17 3l4 4"></path>
                      <path d="M19 5l-4.5 4.5"></path>
                      <path d="M11.5 6.5l6 6"></path>
                      <path d="M16.5 11.5l-6.5 6.5h-4v-4l6.5 -6.5"></path>
                      <path d="M7.5 12.5l1.5 1.5"></path>
                      <path d="M10.5 9.5l1.5 1.5"></path>
                      <path d="M3 21l3 -3"></path>
                    </svg>
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Appointment.type_count('Vaccination') %>
                  </div>
                  <div class="text-muted">
                    Vaccination Appointments
                  </div>
                </div>
              </div>
            </div>
            
            <div class="col-lg-6">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="text-white avatar" style="background-color: #4E97D1"><!-- Download SVG icon from http://tabler-icons.io/i/brand-facebook -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-wand" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M6 21l15 -15l-3 -3l-15 15l3 3"></path>
                      <path d="M15 6l3 3"></path>
                      <path d="M9 3a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2"></path>
                      <path d="M19 13a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2"></path>
                    </svg>                
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Appointment.type_count('Specialist') %>
                  </div>
                  <div class="text-muted">
                    Specialist Appointments
                  </div>
                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
      
      
    <div class="col-lg-6">
      <div class="card p-4">
        <div class="card-body card-body-scrollable card-body-scrollable-shadow">
          <h1> Recent Appointments</h1>
          <p  class="text-primary mt-1">Showing recent appointments</p>
            
        <div class="table-responsive">
          <table class="table table-sm table-borderless card-table table-vcenter text-nowrap datatable">
            <thead>
              <tr>
                <th>Appointment No.</th>
                <th>Booked</th>
                <th>Name</th>
                <th>Date</th>
                <th>Procedure</th>
              </tr>
            </thead>
            <tbody>
              <% if current_user.doctor? %>
                <% current_user.appointments.active.last(10).reverse.each do |appointment| %>
                <tr>
                  <td><%= link_to appointment.appointment_number, appointment_path(appointment) %> </td>
                  <td><%= format_date(appointment.created_at) %> </td>
                  <td><%=appointment.first_name + ' ' + appointment.last_name %> </td>
                  <td><%= format_date(appointment.date) %> </td>
                  <td><%=appointment.procedure.name %> </td>
                </tr>
                <% end %>
              <% else %>
                <% Appointment.active.last(10).reverse.each do |appointment| %>
                <tr>
                  <td><%= link_to appointment.appointment_number, appointment_path(appointment) %> </td>
                  <td><%= format_date(appointment.created_at) %> </td>
                  <td><%=appointment.first_name + ' ' + appointment.last_name %> </td>
                  <td><%= format_date(appointment.date) %> </td>
                  <td><%=appointment.procedure.name %> </td>
                </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
            <%= link_to "All appointments", appointments_path, class:'btn btn-primary mt-4' %>
        </div>
      </div>
      
      
    </div>
  </div>
</div>

app/views/pages/gp.html.erb
<div class="container">
  <div class="row d-flex mt-4">
    <div class="col col-lg-6">
      <h1 class='page-heading peach-underline'> GP Services </h1>
      <p class='heading-text my-4'>Acute infection usually flares up quickly and may require immediate medical attention. 
      This can be anxiety-provoking and difficult to manage, alongside the stresses of everyday life. With the 
      right treatment and care given by a specialist, symptoms can be relieved and managed before they become worse. 
      With Midland Health, you can book an urgent appointment online by sending us an email or over the phone and be seen
      the same day. A friendly GP will provide you with advice or treatment to get you back on your feet as quickly as possible</p>
      <p class='heading-text'>The most common types of acute infection are: </p>
      <h3> Viral Infections</h3>
      <h3> Bacterial Infections</h3>
    </div>
      
    <div class="col col-lg-1">
    <!--- Blank space, prob a better way -->
    </div>
      
    <div class="col col-lg-5">
      <img class="rounded-corner mt-4" alt="Image cap [100%x180]" src="https://midlandhealth.co.uk/wp-content/uploads/2022/05/Midland-Health-151-1-600x400.webp" data-holder-rendered="true" style="height: auto; width: 100%; display: block;">
    </div>
  </div>
  
  <div class="row d-flex my-4">
    <div class="col col-lg-6">
      <h1 class='page-heading peach-underline'>Booking A GP Consultation </h1>
      <p class='heading-text my-4'>Acute infection usually flares up quickly and may require immediate medical attention. 
      This can be anxiety-provoking and difficult to manage, alongside the stresses of everyday life. With the 
      right treatment and care given by a specialist, symptoms can be relieved and managed before they become worse. 
      With Midland Health, you can book an urgent appointment online by sending us an email or over the phone and be seen
      the same day. A friendly GP will provide you with advice or treatment to get you back on your feet as quickly as possible</p>
    </div>
      
    <div class="col col-lg-1">
    <!--- Blank space, prob a better way -->
    </div>
      
    <div class="col col-lg-5">
      
      <div class="" id="sidebar-menu">
            <ul class="navbar-nav pt-lg-3">
              <li class="nav-item accent-bg white-text p-2 nav-top-border">
              </li>
              <% Procedure.find_procedure_by_type(0).each do |procedure| %>
              <li class="nav-item accent-bg white-text p-2">
                <%= link_to procedure.name, procedure_path(procedure), class:"card-text white-text mx-2 dropdown-item" %>
                </li>
              <% end %>
              <li class="nav-item dropdown accent-bg white-text p-2 nav-bottom-border">
              </li>
            </ul>
          </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="justify-content-end text-left">
  <div class="jumbotron bg-overlay">
    <div class="row d-flex">
      <div class="col-lg-6 mt-4" style="padding-left:4em" >
        <div class="glass-card">
          <h1 class="page-heading">Hughes</h1>
          <h1 class="page-heading blue-text">Medical Centre</h1>
          
          <p class="mb-0 card-text">Welcome to Hughes Medical Centre, a private healthcare clinic with a wide range of services
          and compassionate providers. Our services range from cosmetic and reconstructive surgeries, to ambulatory care and 
          counselling.</p>
          <div class="col-auto justify-content-center">
            <%= link_to 'Book GP Appointment', new_appointment_path(procedure_id: 9), class:"btn accent-bg white-text" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


  <div class="row d-flex justify-content-center welcome-neg-top mb-4"> <!--- Features card row -->
    <div class="col-md-3 my-auto p-0">
      <div class="card d-flex welcome-card blue-light-bg">
        <div class="card-body align-items-center justify-content-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M4 5m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path>
            <path d="M16 3l0 4"></path>
            <path d="M8 3l0 4"></path>
            <path d="M4 11l16 0"></path>
            <path d="M10 16l4 0"></path>
            <path d="M12 14l0 4"></path>
          </svg>
          <h1> Appointments </h1>
          <p class='card-text'> Browse our catalog of service offerings, including routine checkups, various tests and screening. We specialize 
          in surgeries, which include cosmetic and reconstructive surgeries. Our staff are always there to help.</p>
        </div>
      </div>
    </div>
    
    
    <div class="col-md-3 my-auto p-0">
      <div class="card d-flex welcome-card blue-mid-bg">
        <div class="card-body align-items-center justify-content-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-cash" width="150%" height="150%" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M7 9m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z"></path>
            <path d="M14 14m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
            <path d="M17 9v-2a2 2 0 0 0 -2 -2h-10a2 2 0 0 0 -2 2v6a2 2 0 0 0 2 2h2"></path>
          </svg>
          <h1> Insurance Options </h1>
          <p class='card-text'>We are proud to partner with major insurance providers on island to ensure that healthcare is more accessible for everyone.
          Insurance policies we accept include Alliance,  Redbridge, Nagico and others.</p>
        </div>
      </div>
    </div>
    
    <div class="col-md-3 my-auto p-0">
      <div class="card d-flex welcome-card blue-darker-bg">
        <div class="card-body align-items-center justify-content-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clock-hour-3" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
            <path d="M12 12h3.5"></path>
            <path d="M12 7v5"></path>
          </svg>
          <h1> Opening Hours </h1>
          <p class='card-text'>We are proud to partner with major insurance providers on island to ensure that healthcare is more accessible for everyone.
          Insurance policies we accept include Alliance,  Redbridge, Nagico and others.</p>
        </div>
      </div>
    </div>
    
  </div><br><br> <!--- end of card row --->
  
<div class="container-xl">
  <h1 class='display-6 fw-bold'>Our Services</h1>

  <div class="row row-deck row-cards page-section pt-0">
    <div class="col-sm-6 col-lg-4">
      <div class="card service-card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class='peach-underline'>Privtate GP Services</h2>
          <p class="card-text py-3">A Pay-As-You-Go same day GP service offering a range of consultations, vaccines and tests for you and your family.</p>
        </div>
        <%= link_to gp_path, class:'card-footer accent-bg text-center' do %>
          <span class='white-text text-center'>Discover our Private Services</span>
        <% end %>
      </div>
    </div>
    
    <div class="col-sm-6 col-lg-4">
      <div class="card service-card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1582719367079-bc1b8e5fed9d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class='peach-underline'>Tests & Diagnostics</h2>
          <p class="card-text py-3">Midland Health offers all Pathology, Radiology and Diagnostics that you may require to help manage your condition.</p>
        </div>
        <%= link_to '#', class:'card-footer accent-bg text-center' do %>
          <span class='white-text text-center'>See our Testing & Diagnostics</span>
        <% end %>
      </div>
    </div>
    
    <div class="col-sm-6 col-lg-4">
      <div class="card service-card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1631941618536-2979d565b726?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class='peach-underline'>Vaccinations</h2>
          <p class="card-text py-3">Our competent practitioners at our Private Vaccination Clinic have experience of working with adults and children, and we offer childhood immunisations as well as adult vaccinations for travel.</p>
        </div>
        <%= link_to '#', class:'card-footer accent-bg text-center' do %>
          <span class='white-text text-center'>See our Vaccination Services</span>
        <% end %>
      </div>
    </div>
    
    <div class="col-sm-6 col-lg-4">
      <div class="card service-card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1516549655169-df83a0774514?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class='peach-underline'>Surgery </h2>
          <p class="card-text py-3">Midland Health provides a number of health check packages to suit a wide range of needs. Our experienced GP’s will provide lifestyle guidance and comprehensive healthcare advice, followed by a report.</p>
        </div>
        <%= link_to '#', class:'card-footer accent-bg text-center' do %>
          <span class='white-text text-center'>Discover our Surgery Services</span>
        <% end %>
      </div>
    </div>
    
    <div class="col-sm-6 col-lg-4">
      <div class="card service-card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1576091160550-2173dba999ef?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img-top" alt="...">
        <div class="card-body ">
          <h2 class='peach-underline'>Specialist Services </h2>
          <p class="card-text py-3">Midland Health provides specialist services for health needs at various life stages. Our experts will guide you whether your concern is about illness or employment/work medicals and travel.</p>
        </div>
        <%= link_to '#', class:'card-footer accent-bg text-center' do %>
          <span class='white-text text-center'>Get Specialized Help</span>
        <% end %>
      </div>
    </div>
    
    <div class="col-sm-6 col-lg-4">
      <div class="card service-card rounded-corner" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1153&q=80" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class='peach-underline'>Contact Us </h2>
          <p class="card-text py-3">When visiting our clinic, please observe the national health and safety protocols and The following process.</p>
        </div>
        <%= link_to '#', class:'card-footer accent-bg text-center' do %>
          <span class='white-text text-center'>See our Details</span>
        <% end %>
      </div>
    </div>
  </div>
</div>