config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end
  
  namespace :appointment do
    get 'steps/show'
    get 'steps/update'
  end
  get 'users/index'
  get 'users/show'
  
  devise_for :users, :skip => [:registration], :controllers => { :users => "users" }
    as :user do
      authenticated :user do
      root "pages#dashboard", as: :authenticated_root
      end
    
      unauthenticated :user do
        root "pages#home", as: :unauthenticated_root
    end
  end
  
  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  
  resources :users, except: [:destroy], concerns: [:with_datatable]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  
  resources :appointments, concerns: [:with_datatable] do
    resources :steps, only: [:show, :update], controller: 'appointment/steps'
    
    member do
      get 'assign_doctor'
      get 'cancel'
    end
  end
  
  
  resources :procedures, concerns: [:with_datatable] do
    member do
      get 'show_timeslots'
    end
  end
  
  
  resources :payments, concerns: [:with_datatable]
    
  
  
  resources :timeslots do
    member do
      get 'remove_time'
    end 
  end
  
 get 'reports/dashboard', to: 'reports#dashboard'
 get 'update_report', to: 'reports#update_report'
 get 'download_appointments_report', to: 'reports#download_appointments_report'
 get 'download_procedures_report', to: 'reports#download_procedures_report'
 get 'download_payments_report', to: 'reports#download_payments_report'
 get 'gp', to: 'pages#gp'
  
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  include ApplicationHelper
  
  has_many :appointments
  has_many :timeslots
    
    enum procedure_type: [:General, :Vaccination, :Test, :Surgery, :Specialist]
    enum is_available: [:Available, :Always_available, :Not_available]
    
    validates :name, :cost, :procedure_type, presence: true;
    
  def format_date(date)
    date.strftime("%b %-d, %Y")
  end
    
  def self.find_procedure_by_type(procedure)
    self.where(procedure_type: procedure)
  end
  
  def find_procedure_type
    self.procedure_type
  end
  
  def today
    Date.current + 1
  end
  
  def available_days
    if self.is_available == 'Always_available'
      today..3.weeks.from_now 
    else
      ((self.start_date - self.end_date).to_i).abs > 21 ? self.start_date..3.weeks.from_now : self.start_date.. self.end_date
    end
  end
  
  def bookable(date, time)
    date = format_date(date.to_date)
    time = format_time(time.to_time)
    Appointment.active.where(date: date, time: time).count < self.booking_limit
  end
  
  def self.procedure_type_count(type)
    self.where(procedure_type: type).count
  end
  
  def self.availability_count(availability)
    self.where(is_available: availability).count
  end
  
  
  
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_procedure, only: [:show, :edit, :update, :destroy, :show_timeslots]
  
  def index
    @procedures = Procedure.all
  end

  def show
  end

  def new
    @procedure = Procedure.new
  end
  
  def create 
    @procedure = Procedure.new(procedure_params)
    if @procedure.save
        flash[:notice] = "Procedure was created successfully."
        redirect_to procedures_path
    else
       render 'new' 
    end
  end
  
  def update
    if @procedure.update(procedure_params)
      flash[:notice] = "Procedure was updated successfully."
      redirect_to procedure_path(@procedure)
    else
      render 'form', appointment: @procedure
    end   
  end

  def edit
  end
  
  def show_timeslots
    
  end
  
  def datatable
    respond_to do |format|
      format.html
      format.json { render json: ProcedureDatatable.new(params, view_context: view_context) }
    end
  end
  
  private
    
    def procedure_params
       params.require(:procedure).permit(:name, :procedure_type, :cost, :is_available, :booking_limit, :start_date, :end_date,
       :description, :details)
    end

    def set_procedure
        @procedure = Procedure.find(params[:id])
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= simple_form_for(@procedure) do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :procedure_type, :collection   => Procedure.procedure_types.keys %>
    <%= f.input :description %>
    <%= f.input :details %>
    <%= f.input :cost %>
    <%= f.input :booking_limit%>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
    <%= f.input :is_available, :collection   => Procedure.is_availables.keys %>
  </div>

  <div class="form-actions mt-2">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/procedures/_modal.html.erb
<div class="modal modal-blur fade" id="<%= modal_id %>" tabindex="-1" aria-hidden="true" style="display: none;">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Add new timeslot for procedure: <%= @procedure.name %></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            
            <%= render 'timeslots/form', timeslot: timeslot  %>
            
          </div>
          <div class="modal-footer">
            <button type="button" class="btn me-auto bg-danger text-white" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

app/views/procedures/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-4">
      <div class="col col-lg-12">
          <div class="card">
            <div class="card-body">
              <%= render 'shared/page_header', pre_title: "Manage Procedure", title: "Editing #{@procedure.name}", back_action: procedures_path %>
              <%= render 'form', procedure: @procedure %>
              
              <%= link_to show_timeslots_procedure_path(@procedure), class:'btn btn-primary d-none d-sm-inline-block my-4' do %>
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clock-record" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path d="M21 12.3a9 9 0 1 0 -8.683 8.694"></path>
                  <path d="M12 7v5l2 2"></path>
                  <path d="M19 19m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                </svg>
                <span> Edit timeslots</span>
              <% end %>
            </div>
          </div>
      </div>
  </div>
</div>

app/views/procedures/index.html.erb
<div class="container">
  <div class="row justify-content-md-center my-4">
      <div class="col col-lg-12">
        <div class="card">
          <div class="card-body">
            <%= render 'shared/page_header', pre_title: "Overview", title: 'Procedures', action: new_procedure_path, action_name: "New Procedure" %>
          </div>
          <div class="table-responsive">
            <table id="procedure-datatable" class="table table-vcenter card-table table-striped text-nowrap center" data-source="<%= datatable_procedures_path(format: :json) %>" style='width:100%;'>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Type</th>
                  <th>Cost</th>
                  <th>Availability</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @procedures.each do |procedure| %>
                  <tr>
                    <td><%=procedure.name %> </td>
                    <td><%=procedure.procedure_type %> </td>
                    <td><%=procedure.cost %> </td>
                    <td class="text-end">
                      <span class="dropdown">
                        <button class="btn dropdown-toggle align-text-top" data-bs-boundary="viewport" data-bs-toggle="dropdown">Actions</button>
                        <div class="dropdown-menu dropdown-menu-end">
                          <a class="dropdown-item" href="#">
                            Action
                          </a>
                          <a class="dropdown-item" href="#">
                            Another action
                          </a>
                        </div>
                      </span>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/procedures/new.html.erb
<div class="container">
  <div class="row justify-content-md-center my-4">
    <div class="col col-lg-12">
      <div class="card">
        <div class="card-body">
            <%= render 'shared/page_header', pre_title: "Manage procedure", title: "Adding procedure", back_action: procedures_path %>
          
          <%= render 'procedures/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/procedures/show.html.erb
<% if current_user %>
  <div class="container">
      <div class="row justify-content-md-center mt-4">
        <div class="col col-lg-12">
          <div class="card">
            <div class="card-header">
              <%= render 'shared/page_header', pre_title: "Procedure", title: "#{@procedure.name}", back_action: appointments_path %>
            </div>
            <div class="card-body mb-4">
              <div class="row ">
                <div class="col-sm">  
                  <b><p> Type:</p></b>
                  <p class="text-muted"><%= @procedure.procedure_type %></p>
                </div>
                
                <div class="col-sm">  
                  <b><p> Cost:</p></b>
                  <p class="text-muted"><%= @procedure.cost %></p>
                </div>
              </div>
                <b><p> Description:</p></b>
                <p class="text-muted"><%= @procedure.description %></p>
                
              <div class="row">
                <b><p> Details:</p></b>
                <p class="text-muted"><%= @procedure.details %></p>
              </div>
              
              <div class="row">
                <div class="col-sm">  
                  <b><p> Booking limit:</p></b>
                  <p class="text-muted"><%= @procedure.booking_limit %></p>
                </div>
                
                <div class="col-sm">  
                  <b><p> Availability:</p></b>
                  <% if @procedure.is_available == 'Available' %>
                    <span class="badge badge-sm bg-success">Available</span>
                  <% elsif @procedure.is_available == 'Always_available' %>
                    <span class="badge badge-sm bg-success">Always available</span>
                  <% else %>
                    <span class="badge badge-sm bg-danger">Unvailable</span>
                  <% end %>
                </div>
              </div>
              <div class="row">
                <div class="col-sm">  
                  <b><p> Start date:</p></b>
                  <p class="text-muted"><%= @procedure.start_date %></p>
                </div>
                <div class="col-sm">  
                  <b><p> End date:</p></b>
                  <p class="text-muted"><%= @procedure.end_date %></p>
                </div>
              </div>
              
              <!---- Time slots --->
              <div class="row ">
                <div class="col-sm">  
                  <b><p> Times:</p></b>
                </div>
              </div>
              
              <% if @procedure.timeslots.count > 0 %>
                <div class="row row-deck row-cards">
                  <% @procedure.timeslots.order(:day).each do |timeslot| %>
                    <div class=" col-lg-3">
                      <div class="card bg-light">
                        <div class="card-body">
                          <div class="">
                            <p><b><%= timeslot.day %></b></p>
                            <% timeslot.time.sort.each do |t| %>
                            <div class="row mb-1">
                              <div class="col-auto my-auto">
                                <span class=''><%= t %></span>
                              </div>
                            </div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <p> No procedure times yet. </p>
              <% end %>
              <!---- End time slots --->
            </div>
            
            
            <!-- Card footer -->
          <div class="card-footer">
            <div class="row align-items-center">
              <div class="col-auto">
                <%= link_to 'Edit Procedure Details', edit_procedure_path(@procedure) %>
              </div>
              
              <div class="col-auto">
                <b><%= link_to 'Delete Procedure', procedure_path(@procedure, method: :delete, data:{confirm: "Are you sure?"}),  class:'text-danger' %></b>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
<% else %>

  <div class="container">
    <div class="row mt-4">
      <div class="col col-lg-8">
        <h1 class='page-heading peach-underline'><%=  @procedure.name %></h1>
        <p class='heading-text my-4'><%= @procedure.description %></p>
        <p class='heading-text'><%= @procedure.details %></p>
        
        
        <div class="page-section">
          <h1 class='page-heading peach-underline'>Pricing</h1>
          
          <div class='col col-sm-4'>
            <div class="card my-4 shadow-lg rounded-corner">
              <div class="card-body">
                <h1 class='peach-underline mt-4'> Standard GP Consultation</h1>
                <h1 class='page-heading my-4'>$<%= @procedure.cost %></h1>
                
                <% if @procedure.is_available != 'Not_available' %>
                  <%= link_to 'Book Now', new_appointment_path(procedure_id: @procedure), class:'btn btn-lg accent-bg white-text mb-4' %>
                <% else %>
                  <p class='heading-text mb-0'> Service currently unavailable </p>
                  <%= link_to 'Let me know when this service is available', '#', class:'small text-muted fw-bold' %>
                <% end %>
                
                
                
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="col col-lg-1">
        <!--- Blank space, prob a better way -->
      </div>
      
      <div class="col col-lg-3">
        <div class="" id="sidebar-menu">
            <ul class="navbar-nav pt-lg-3">
              <li class="nav-item accent-bg white-text p-2 nav-top-border">
              </li>
              <% Procedure.find_procedure_by_type(@procedure.procedure_type).each do |procedure| %>
              <li class="nav-item accent-bg white-text p-2">
                <%= link_to procedure.name, procedure_path(procedure), class:"card-text white-text mx-2 dropdown-item" %>
                </li>
              <% end %>
              <li class="nav-item dropdown accent-bg white-text p-2 nav-bottom-border">
              </li>
            </ul>
          </div>
      </div>
        
      </div>
    </div>
  </div>
<% end %>

app/views/procedures/show_timeslots.html.erb
<div class="container">
    <div class="row justify-content-md-center mt-4">
      <div class="col col-lg-12">
        <div class="card">
          <div class="card-body">
            <%= render 'shared/page_header', pre_title: "Manage Procedure", title: "Timeslots for #{@procedure.name}", back_action: procedures_path %>

           <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#new_timeslot">
             <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clock-record" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M21 12.3a9 9 0 1 0 -8.683 8.694"></path>
                <path d="M12 7v5l2 2"></path>
                <path d="M19 19m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
              </svg>
              Add timeslot
            </a>
        
            <%= render 'procedures/modal', modal_id: "new_timeslot", timeslot: Timeslot.new %>

            <div class="row row-deck row-cards my-4">
              <% @procedure.timeslots.order(:day).each do |timeslot| %>
                <div class="col-sm-6 col-lg-3">
                  <div class="card">
                    <div class="card-body">
                      <div class="">
                        <p><b><%= timeslot.day %></b></p><br>
                        <% timeslot.time.sort.each do |t| %>
                        <div class="row mb-1">
                          <div class="col-sm-4 my-auto">
                            <span class='btn'><%= t %></span>
                          </div>
                          <div class="col-sm-6 my-auto">
                            <span>
                              <%= link_to remove_time_timeslot_path(timeslot, time_param: t), data: { turbo_confirm: "Are you sure?" } do %>
                                <svg xmlns="http://www.w3.org/2000/svg" class=" badge badge-sm bg-danger p-0" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                  <path d="M18 6l-12 12"></path>
                                  <path d="M6 6l12 12"></path>
                                </svg>
                              <% end %>
                            </span>
                          </div>
                        </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="card-footer">
                      <a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#<%= "procedure-timeslot-#{timeslot.id}" %>">
                       <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clock-record" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                          <path d="M21 12.3a9 9 0 1 0 -8.683 8.694"></path>
                          <path d="M12 7v5l2 2"></path>
                          <path d="M19 19m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                        </svg>
                        Add time
                      </a>
                      
                      <%= render 'procedures/modal', modal_id: "procedure-timeslot-#{timeslot.id}", timeslot: timeslot %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>