config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end
  
  namespace :appointment do
    get 'steps/show'
    get 'steps/update'
  end
  get 'users/index'
  get 'users/show'
  
  devise_for :users, :skip => [:registration], :controllers => { :users => "users" }
    as :user do
      authenticated :user do
      root "pages#dashboard", as: :authenticated_root
      end
    
      unauthenticated :user do
        root "pages#home", as: :unauthenticated_root
    end
  end
  
  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  
  
  resources :users, except: [:destroy], concerns: [:with_datatable]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  
  resources :appointments, concerns: [:with_datatable] do
    resources :steps, only: [:show, :update], controller: 'appointment/steps'
    
    member do
      get 'assign_doctor'
      get 'cancel'
    end
  end
  
  
  resources :procedures, concerns: [:with_datatable] do
    member do
      get 'show_timeslots'
    end
  end
  
  
  resources :payments, concerns: [:with_datatable]
    
  
  
  resources :timeslots do
    member do
      get 'remove_time'
    end 
  end
  
 get 'reports/dashboard', to: 'reports#dashboard'
 get 'update_report', to: 'reports#update_report'
 get 'download_appointments_report', to: 'reports#download_appointments_report'
 get 'download_procedures_report', to: 'reports#download_procedures_report'
 get 'download_payments_report', to: 'reports#download_payments_report'
 get 'gp', to: 'pages#gp'
  
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :procedure
    has_one :payment, dependent: :destroy
    belongs_to :user, optional: true
    
    before_create :generate_appointment_number
    
    cattr_accessor :appointment_steps do
      %w[appointment_information timeslots review pay]
    end
    
    enum status: [:active, :inactive, :cancelled]
    
    attr_accessor :appointment_step
    
    validates :first_name, :last_name, :date_of_birth, :gender, :phone, :email, :procedure_id, presence: true,
      if: -> { required_appointment_step?(:appointment_information)}
        
    validates :time, :date, presence: true,
    if: -> { required_appointment_step?(:timeslots)}
    
    def generate_appointment_number
      begin
        self.appointment_number = "HMCAP-#{[*'A'..'Z', *0..9].sample(6).join}"
      end while self.class.exists?(appointment_number: appointment_number)
    end
    
    def name
      "#{first_name} #{last_name}"
    end
    
    def self.active
      self.where(status: self.statuses[:active])
    end
    
    def self.cancelled
      self.where(status: self.statuses[:cancelled])
    end
    
    def appointment_cost
      self.procedure.cost
    end
    
    def booked_by
      "#{first_name} #{last_name}"
    end
    
    
    def is_today?
      format_date(self.date) == format_date(Date.today)
    end
  
    def is_before_today?
      format_date(self.date) < format_date(Date.today)
    end
  
    def is_after_today?
      format_date(self.date) > format_date(Date.today)
    end
    
    def self.is_today_count
      self.where(date: Date.today).count
    end
  
    def self.is_after_today_count
      self.where('date > ?', Date.today).count
    end
  
    def self.is_before_today_count
      self.where('date < ?', Date.today).count
    end
    
    def self.type_count(type)
      self.active.joins(:procedure).where('procedures.procedure_type.key' => type).count
    end
    
    def self.procedure_count(procedure)
      self.active.joins(:procedure).where('procedures.name' => procedure).count
    end
    
    def self.most_procedure(index)
      max = self.active.group(:procedure_id).count.max_by(index){ |obj| obj[1]}
      max[index-1] != nil ? max[index-1].first : nil
    end
    
    def self.most_procedure_total(index)
      max = self.active.joins(:procedure).group(:procedure_id).sum(:cost).max_by(index){ |obj| obj[1]}
      max[index-1] != nil ? max[index-1].second : nil
    end
    
    def self.most_procedure_payments(index)
      max = self.active.joins(:procedure).group(:procedure_id).sum(:cost).max_by(index){ |obj| obj[1]}
      max[index-1] != nil ? max[index-1].first : nil
    end
    
    private
    
    def required_appointment_step?(step)
      return true if appointment_step.nil?
      return true if self.appointment_steps.index(step.to_s) <= self.appointment_steps.index(appointment_step)
    end
end

app/controllers/appointment/steps_controller.rb
class Appointment::StepsController < ApplicationController
  include Wicked::Wizard
  steps *Appointment.appointment_steps
  
  skip_before_action :authenticate_user!, only: %i[show update]
  before_action :set_appointment, only: %i[show update]
  
  def show
    render_wizard
  end

  def update
    @appointment.update(appointment_params(step))
    render_wizard @appointment
  end
  
  private

  def set_appointment
    @appointment = Appointment.find(params[:appointment_id])
  end
  
  def appointment_params(step)
    permitted_attributes = case step
      when "appointment_information"
        [:first_name, :last_name, :date_of_birth, :gender, :phone, :email, :procedure_id, :user_id]
      when "timeslots"
        [:date, :time]
      end
    params.require(:appointment).permit(permitted_attributes).merge(appointment_step: step)
  end
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    
  skip_before_action :authenticate_user!, only: [:new, :create, :update]
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :assign_doctor, :cancel]
  
  def new
    @appointment = Appointment.new
    if params[:procedure_id]
      @appointment.procedure_id = params[:procedure_id]
    end
      
    @appointment.save(validate: false)
    redirect_to appointment_step_path(@appointment, Appointment.appointment_steps.first)
  end
  

  
  def index 
     @appointments = Appointment.active.all 
  end
  
  def edit
    
  end
  
  def update
    if @appointment.update(appointment_params)
      flash[:notice] = "Appointment was updated successfully."
      redirect_to appointment_path(@appointment)
    else
      render 'edit', appointment: @appointment
    end    
  end
  
  def destroy 
      @appointment.destroy
      redirect_to appointments_path
  end
  
  def cancel
    if @appointment.status == 'active'
      @appointment.status = 'cancelled'
      if @appointment.save
        flash[:notice] = "Appointment was cancelled successfully"
        redirect_to appointments_path(status:'cancelled')
      else
        flash[:notice] = "Appointment was not saved due to an error"
        redirect_to appointments_path
      end
    else
      @appointment.status = 'active'
      if @appointment.save
        flash[:notice] = "Appointment cancellation reversal was successful"
        redirect_to appointments_path
      else
        flash[:notice] = "Appointment was not saved due to an error"
        redirect_to appointments_path(status:'cancelled')
      end
    end
  end
  
  def assign_doctor
    
  end
  
  def datatable
    respond_to do |format|
      format.html
      format.json { render json: AppointmentDatatable.new(params, view_context: view_context, current_user: current_user, status: params[:status]) }
    end
  end
  
  
  private
  
  def appointment_params
     params.require(:appointment).permit(:first_name, :last_name, :date_of_birth, :gender, :phone, :email, :date, :time, 
      :appointment_number, :procedure_id, :user_id)
  end

  def set_appointment
      @appointment = Appointment.find(params[:id])
  end
    
end

app/helpers/appointment/steps_helper.rb
module Appointment::StepsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_all-appointments.html.erb
<tbody>
  <% @appointments.each do |appointment| %>
    <tr>
      <td><%=format_date(appointment.created_at) %> </td>
      <td><%=appointment.appointment_number %> </td>
      <td><%=appointment.first_name %> </td>
      <td><%=appointment.last_name %> </td>
      <td><%=format_date(appointment.date) %> </td>
      <td><%=format_time(appointment.time) %> </td>
      <% if appointment.procedure %>
        <td><%=appointment.procedure.name %> </td>
      <% else %>
        <td></td>
      <% end %>
      <td> 
        <% if appointment.user %>
          <%= appointment.user.name %>
        <% else %>
          <%= link_to 'Assign Doctor', assign_doctor_appointment_path(appointment), class:'badge bg-danger' %>
        <% end %>
      </td>
      <td class="text-end">
        <span class="dropdown">
          <button class="btn dropdown-toggle align-text-top" data-bs-boundary="viewport" data-bs-toggle="dropdown">Actions</button>
          <div class="dropdown-menu dropdown-menu-end">
            <%= link_to 'View', appointment_path(appointment), class:'dropdown-item' %>
            <%= link_to 'Edit', edit_appointment_path(appointment), class:'dropdown-item' %>
            <% if !appointment.user %>
              <%= link_to 'Assign Doctor', assign_doctor_appointment_path(appointment), class:'dropdown-item' %>
            <% end %>
          </div>
        </span>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/appointments/_doctor-appointments.html.erb
<tbody>
  <% current_user.appointments.active.each do |appointment| %>
    <tr>
      <td><%=appointment.created_at %> </td>
      <td><%=appointment.appointment_number %> </td>
      <td><%=appointment.first_name %> </td>
      <td><%=appointment.last_name %> </td>
      <td><%=appointment.date %> </td>
      <td><%=appointment.time %> </td>
      <% if appointment.procedure %>
        <td><%=appointment.procedure.name %> </td>
      <% else %>
        <td></td>
      <% end %>
      <td> 
        <% if appointment.user %>
          <%= appointment.user.name %>
        <% else %>
          <%= link_to 'Assign Doctor', assign_doctor_appointment_path(appointment), class:'badge bg-danger' %>
        <% end %>
      </td>
      
      <!---------- Actions --------->
      <td>
        <span class="dropdown">
          <button class="btn dropdown-toggle align-text-top" data-bs-boundary="viewport" data-bs-toggle="dropdown">Actions</button>
          <div class="dropdown-menu dropdown-menu-end">
            <%= link_to 'View', appointment_path(appointment), class:'dropdown-item' %>
            <%= link_to 'Edit', edit_appointment_path(appointment), class:'dropdown-item' %>
            <% if !appointment.user %>
              <%= link_to 'Assign Doctor', assign_doctor_appointment_path(appointment), class:'dropdown-item' %>
            <% end %>
          </div>
        </span>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>

  <h3>Appointment Information</h3>
  <div class="form-inputs">
    <%= f.input :appointment_number %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :date_of_birth, as: :date, html5: true %>
    <%= f.input :gender, as: :radio_buttons, wrapper: :vertical_collection_inline, collection: User::GENDER %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :date, as: :date, html5: true %>
    <%= f.input :time, as: :time, html5: true %>
    
    <% if @appointment.procedure_id %>
      <%= f.input :procedure_id, as: :hidden, :input_html => { :value => @appointment.procedure_id } %>
    <% else %>
      <%= f.input :procedure_id, collection: Procedure.all %>
    <% end %>
    
    <% if current_user %>
      <%= f.input :user_id, collection: User.doctors  %>
    <% end %>
  </div>

  <div class="form-actions mt-2">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/assign_doctor.html.erb
<div class="container">
  <div class="row justify-content-md-center my-4">
    <div class="col col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= render 'shared/page_header', pre_title: "Manage Appointment", title: "Assigning doctor", back_action: appointments_path %>
    
          <%= simple_form_for(@appointment) do |f| %>
          
            <h3>Assign doctor</h3>
            <div class="form-inputs">
              <%= f.input :user_id, collection: User.doctors  %>
            </div>
          
            <div class="form-actions mt-2">
              <%= f.button :submit %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/create_result.html.erb
<div class="container">
  <div class="row justify-content-md-center my-4">
    <div class="col col-lg-12">
      <h1 class='display-6 mb-4'>Add results</h1>
      
      <%= simple_form_for(@result) do |f| %>
        <div class="form-inputs">
          <%= f.input :result_date %>
          <%= f.input :result_outcome %>
          <%= f.input :comments %>
        </div>
      
        <div class="form-actions mt-2">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appointments/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center my-4">
    <div class="col col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= render 'shared/page_header', pre_title: "Manage Appointment", title: "Editing appointment #{@appointment.appointment_number}", back_action: appointments_path %>
          <%= render 'form', appointment: @appointment %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="container">
  
  <div class="row justify-content-md-center my-4">
    <div class="col col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= render 'shared/page_header', pre_title: "Overview", title: 'Appointments', action: new_appointment_path, action_name: "New Appointment" %>
          
          <div class="row row-cards my-4">
            <div class="col-md-6 col-xl-3">
              <div class="card card-sm">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <span class="bg-blue text-white avatar">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-notebook" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                          <path d="M6 4h11a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-11a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1m3 0v18" />
                          <line x1="13" y1="8" x2="15" y2="8" />
                          <line x1="13" y1="12" x2="15" y2="12" />
                        </svg>
                      </span>
                    </div>
                    <div class="col">
                      <div class="font-weight-medium">
                         <%= Appointment.active.count %>
                      </div>
                      <div class="text-muted">
                        Total Appointments
                      </div>
                    </div>
                  </div>
                </div>
              </div><!--/.card-->
            </div><!--/.col-->

            <div class="col-md-auto col-xl-auto">
              <div class="row align-items-center">
                <div class="col-auto">
                </div>
                <div class="col">
                  <div class="font-weight-medium mb-2">
                    <% if current_page?(appointments_path(status: 'cancelled')) %>
                      <%= link_to 'Active Appointments', appointments_path, class:"btn btn-sm btn-secondary" %> 
                      <%= link_to 'Cancelled Appointments', appointments_path(status:'cancelled'), class:"btn btn-sm btn-primary" %>
                    <% else %>
                      <%= link_to 'Active Appointments', appointments_path, class:"btn btn-sm btn-primary" %> 
                      <%= link_to 'Cancelled Appointments', appointments_path(status:'cancelled'), class:"btn btn-sm btn-secondary" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div><!--/.col-->
          </div><!--/.row-->
          
        </div>
        <div class="table-responsive">
          <table id="appointment-datatable" class="table table-vcenter card-table table-striped text-nowrap datatable" data-source="<%= datatable_appointments_path(status: params[:status], format: :json) %>" style='width:100%;'>
            <thead>
              <tr>
                <th>Booked At</th>
                <th>Appointment No.</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Date</th>
                <th>Time</th>
                <th>Procedure</th>
                <th>Doctor</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="container">
  <div class="row justify-content-md-center my-4">
    <div class="col col-lg-6">
      <h1 class='display-6 mb-4'>Booking <% if params[:procedure_id] %> <%= Procedure.find(params[:procedure_id]).name %> <% end %> Appointment</h1>
      <%= render 'appointments/form' %>
    </div>
  </div>
</div>

app/views/appointments/show.html.erb
<div class="container">
    <div class="row justify-content-md-center my-4">
      <div class="col col-lg-12">
        <div class="card">
          <div class="card-body">
            <%= render 'shared/page_header', pre_title: "Appointment", title: "#{@appointment.booked_by} - #{@appointment.appointment_number}", back_action: appointments_path %>
            
            <h2> Patient Information </h2>
            <div class="row ">
              <div class="col-sm">  
                <b><p> First name:</p></b>
                <p class="text-muted"><%= @appointment.first_name %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Last name:</p></b>
                <p class="text-muted"><%= @appointment.last_name %></p>
              </div>
            </div>
            
            <div class="row ">
              <div class="col-sm">  
                <b><p> Gender:</p></b>
                <p class="text-muted"><%= @appointment.gender %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Date of birth:</p></b>
                <p class="text-muted"><%= @appointment.date_of_birth %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Email:</p></b>
                <p class="text-muted"><%= @appointment.email %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Phone:</p></b>
                <p class="text-muted"><%= @appointment.phone %></p>
              </div>
            </div>
            
            <h2> Appointment Information </h2>
            <div class="row ">
              <div class="col-sm">  
                <b><p> Apointment date:</p></b>
                <p class="text-muted"><%= format_date(@appointment.date) %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Apointment time:</p></b>
                <p class="text-muted"><%= format_time(@appointment.time) %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Procedure:</p></b>
                <p class="text-muted"><%= @appointment.procedure ? @appointment.procedure.name : "Nothing yet" %></p>
              </div>
              
              <div class="col-sm">  
                <b><p> Created at:</p></b>
                <p class="text-muted"><%= @appointment.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
              
              <% if @appointment.user %>
                <div class="col-sm">  
                  <b><p> Doctor:</p></b>
                  <p class="text-muted"><%= @appointment.user.name %></p>
                </div>
              <% end %>
            </div>
          </div>
    
        <!-- Card footer -->
        <div class="card-footer">
          <div class="row">
            <div class="col-auto">
              <%= link_to 'Edit Appointment Details', edit_appointment_path(@appointment) %>
            </div>
            
            <div class="col-auto">
              <%= link_to 'View Payment', payment_path(@appointment.payment) %>
            </div>
            
            <% if !@appointment.user %>
              <div class="col-auto">
                <%= link_to 'Assign Doctor', assign_doctor_appointment_path(@appointment) %>
              </div>
            <% end %>
            
            <% if @appointment.status == 'active' %>
              <div class="col-auto">
                <%= link_to 'Cancel Appointment', cancel_appointment_path(:appointment_id => @appointment.id), data: { confirm: "Are you sure?" } %>
              </div>
            <% else %>
            <div class="col-auto">
              <%= link_to 'Reverse Cancellation', cancel_appointment_path(:appointment_id => @appointment.id), data: { confirm: "Are you sure?" } %>
            </div>
            <% end %>
              
            <div class="col-auto">
              <b><%= link_to 'Delete Appointment', appointment_path(@appointment, method: :delete, data:{confirm: "Are you sure?"}),  class:'text-danger' %></b>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>